### ISSUE TITLE
"Perhaps WP Engine should have consider that before suing us" after taking down the plugin

### ISSUE THREAD

**Issue by NewsGuyTor** [bullenweg/bullenweg.github.io#1]
This quote is pretty stunning, should be featured.

Matt: "Perhaps WP Engine should have consider that before suing us.", a reply from Matt to negative reaction to the plugin takeover. 

https://news.ycombinator.com/item?id=41821336#41821870

**Comment by pothi** [comment]
Possibly related... https://x.com/WordPress/status/1845285782128341285 (posted by official WP account)

Quote from the tweet...

> Access could be restored immediately if they dropped their legal suits against us.

**Comment by fluffy-critter** [comment]
Mr. Legal Expert surely understands the difference between a lawsuit and a C&D?
