### ISSUE TITLE
Nosebleed Stuff

### ISSUE THREAD

**Issue by yobada** [bullenweg/bullenweg.github.io#11]
I'd suggest removing the nosebleed bit. I don't think it fits, "lied, misrepresented or behaved in a questionable manner" especially since it happened after traveling.  It is a pretty normal occurrence and takes away from the more valid points in the timeline. Thank you.

**Comment by ghost** [comment]
<img width="591" alt="Screenshot 2024-10-16 at 00 06 48" src="https://github.com/user-attachments/assets/99cd5b00-c6d4-4d22-b16e-380292e31a63">
