### ISSUE TITLE
Seeking a new maintainer

### ISSUE THREAD

**Issue by ghost** [bullenweg/bullenweg.github.io#12]
Feedback from reddit and email is that the website should be a list of facts without commentary. I made bullenweg.com to channel my frustration with Matt and his conduct. The web site is not intended to be impartial or objective but people are using the web site as an encyclopedia instead of an antidote to Matt and his Bullenweg. I would rather spend time with my family than maintain a list of facts. It is time to hand over the torch to persons aligned with the will of the people. 

Volunteers to take over, make yourselves known.

**Comment by ghost** [comment]
@DoctorOgg can I bestow the responsibility upon you?

**Comment by DoctorOgg** [comment]
let me think about it..

**Comment by ghost** [comment]
@ryancduff would you like to run the site?

**Comment by ryancduff** [comment]
I would suggest you maintain and you do you. There are a few resources I've seen, some unbiased, some commentary. 

And besides, I would not be able to "facts-only" 

Perhaps just add an addendum with links to other places like mullenweg.wtf

**Comment by ghost** [comment]
> Perhaps just add an addendum with links to other places like mullenweg.wtf

Good idea. I'll do that instead. Bullenweg.com will retain its unprofessional spirit. The title is updated.

https://bullenweg.com/#alternative-websites
