### ISSUE TITLE
Quote source attribution missing

### ISSUE THREAD

**Issue by mattbeck** [bullenweg/bullenweg.github.io#13]
The quote from this attorney has no documented source

> Susan Rubenstein, attorney representing the nurses in "Those Other Lawsuits", addresses Matt's response.

**Comment by mattbeck** [comment]
No reason to suspect it didn't originate from her, but crossing t's and dotting i's, and citing sources seem important here.

**Comment by ghost** [comment]
I sent her an email to the email address included in the legal filings, I asked for a response to be published on the website.

**Comment by ghost** [comment]
> No reason to suspect it didn't originate from her, but crossing t's and dotting i's, and citing sources seem important here.

I am not sure how best to cite it. "Via email"? I usually cite back to the source so that readers can follow the trail, in this case bullenweg.com is the source.

**Comment by mattbeck** [comment]
Perhaps screenshot the email, if needed redact personal details and link to that.

**Comment by sheatsb** [comment]
^ That part. Please cite and source appropriately. 
It just makes it easier for the case being made. Not that I don't believe it - I've been the subject of Matt's low key racism and witness to his use of women as props before.

**Comment by ghost** [comment]
A screenshot does not verify the integrity of the response. [@MightBeDwelling](https://x.com/MightBeDwelling) on Twitter has independently reached out to Susan, once they provide independent confirmation that the response is genuine I will update the website to include that independent confirmation.

**Comment by itsdrewmiller** [comment]
It stuck out to me too that it was completely unsourced, but just putting "I reached out to Rubenstein for comment" or whatever is fine.  You don't have to cryptographically prove the chain of custody here.

**Comment by ghost** [comment]
Added the following:

> Response provided by email at 16 Oct 2024 03:15:03 +0000 from Susan@susanrubensteinlaw.com.
