### ISSUE TITLE
Source missing re: poaching WPE employees

### ISSUE THREAD

**Issue by adrienne** [bullenweg/bullenweg.github.io#14]
Could you add a source to this part? And ideally a screencap of the Slack chat?

https://bullenweg.com/#matt-plans-to-poach-wp-engine-employees

**Comment by ghost** [comment]
The source is the same source of earlier leaks from Slack which were later independently verified (by the [Employees Describe an Environment of Paranoia and Fear Inside Automattic Over WordPress Chaos](https://www.404media.co/automattic-buyout-offer-wordpress-matt-mullenweg/) article). The source is transcribing the messages to avoid any possibility of being traced back based on timestamps etc. given Matt's goal of tracking down leakers using any means possible.

Do you have a suggestion for how best to represent this on the website?

**Comment by ghost** [comment]
From Kellie on Twitter:

https://x.com/kellie/status/1847477754671092096

> AntiMATTIC and Bullenweg both have the scoop on the way that Mr. Mullenweg is treating the people who accepted his most recent exit offer and his plans to poach more [@wpengine](https://x.com/wpengine) employees. Shameful.
>
> [@nlrb](https://x.com/NLRB) [@NLRBGC](https://x.com/NLRBGC) [#automattic](https://x.com/search?q=%23automattic) 
>
> https://antimattic.net/index.php/2024/10/19/get-the-f-out-baby-please-dont-go/

Per their about page:

> Who posts on antimattic.net?
> Verified ex-employees of Automattic

The post on antimattic.net includes additional information that hasn't yet appeared on bullenweg.com, I will update bullenweg.com with the quotes from antimattic.net and use that as the source.

**Comment by ghost** [comment]
Updated with link to antimattic.net: https://bullenweg.com/#matt-plans-to-poach-wp-engine-employees 

@adrienne antimattic.net is a better source as it also has additional context.
