### ISSUE TITLE
Wage Theft and Abuse Lawsuit

### ISSUE THREAD

**Issue by thatspacepirate** [bullenweg/bullenweg.github.io#15]
https://webapps.sftc.org/ci/CaseInfo.dll?CaseNum=CGC22600095&SessionID=196E27677FADAB76B0A3E34867EA971DE955D44A
Not sure if this was already known about but there were some recent developments and it's been gaining some infamy recently.

**Comment by jacques** [comment]
This lawsuit is already listed under the list of lawsuits.
