### ISSUE TITLE
Domain deactivated

### ISSUE THREAD

**Issue by ghost** [bullenweg/bullenweg.github.io#18]
The bullenweg.com domain has been deactivated by Porkbun, the registrar :( some mirrors are here https://mastodon.social/@mvsde/113373682248521134

Since https://bullenweg.github.io redirects to https://bullenweg.com, this makes the site un-visitable.

Any info on why Porkbun deactivated it? This makes me regret having moved my domains to Porkbun recently.

**Comment by pothi** [comment]
Thanks for the heads-up.

All registrars must adhere to legal requests. One of my domains is with Porkbun as well. It is too early to put the blame on Porkbun alone. Let's see if there is any additional info.

**Comment by ghost** [comment]
I am the original owner of the domain. The deletion has nothing to do with Porkbun. Porkbun are a great, privacy conscious registrar. I highly recommend Porkbun. I deleted the domain because I do not want to be involved in Matt's war on WordPress any more. I did not plan to comment about removing the domain but I cannot let my beloved registrar Porkbun take any blame or suspicion.

cc @adrienne
