### ISSUE TITLE
Tumblr drama a few months ago

### ISSUE THREAD

**Issue by nukeop** [bullenweg/bullenweg.github.io#2]
https://techcrunch.com/2024/02/22/tumblr-ceo-publicly-spars-with-trans-user-over-account-ban-revealing-private-account-names-in-the-process

https://www.reddit.com/r/CuratedTumblr/comments/1az9tp7/tumblr_staff_have_issued_a_statement_regarding

He went ballistic earlier this year, do you think this is in scope?

**Comment by fluffy-critter** [comment]
Here's another article about it. Given that the stuff about the nurse is considered germane, this certainly is too. https://mashable.com/article/tumblr-transphobia-matt-mullenweg?test_uuid=01iI2GpryXngy77uIpA3Y4B&test_variant=a

**Comment by thatspacepirate** [comment]
https://www.dropbox.com/scl/fo/pyh4ca4v4mc0ggrklgd0i/h?rlkey=2se1p4911irku3mw42sp8htrz&e=1&dl=0

Here's a Dropbox link I got from [Tumblr](https://www.tumblr.com/carhammerexplosionmatt/742898907217117184/photomatt-screenshots?source=share) with screenshots of everything that happened. **warning - matt talks about a lot of nsfw stuff in these**

To be honest I think reducing this to Tumblr drama isn't helpful, this was Matt harassing a transgender woman who was already a target of harassment and then following that person to Twitter.

**Comment by ghost** [comment]
https://bullenweg.com/#argues-with-trans-tumblr-user-and-reveals-their-private-accounts
