### ISSUE TITLE
Lawsuit Festinger Vault

### ISSUE THREAD

**Issue by charizard293** [bullenweg/bullenweg.github.io#9]
https://festingervault.com/

https://meta.festingervault.com/t/important-server-outage-of-data-center/104457

###

Hey Festinger Vault Family,

We wanted to let you know about a temporary situation with our services.

Due to a legal claim from Automattic (WordPress) and WooCommerce regarding trademark usage and GPL compliance, we are forced to hold our offerings to prevent the risk of fines temporarily.

Our lawyers have requested the court’s decision to deny Automattics and WooCommerce’s claims that contradict the open-source philosophy.
The Court hearing will occur on 2 October 2024, and a verdict is expected soon.

In the meantime, we are negotiating with Automattic and WooCommerce to get back on track as soon as possible.

But don’t worry—this is a brief pause, and we’re not going anywhere!
Festinger Vault is still 100% dedicated to providing GPL-compliant, open-source plugins and themes for WordPress, and we’re confident in the legal process.

What’s coming next?

We’re moving our servers to a brand-new data center by the end of this week for better speed and reliability.

A stable plugin with all unique features is on track to launch right when we’re back up and running!

In the meantime, if you need any assistance or have questions, feel free to reach out at
[hello@festingervault.com](mailto:hello@festingervault.com) or join the conversation in our Festinger Vault Community,
where we’re always happy to help.

We’re excited to return even more robust and better, with excellent new features and improvements.
Thanks for sticking with us—we genuinely appreciate your support.

Stay tuned for more updates, and we can’t wait to welcome you back soon!

Cheers,
The Festinger Vault Team

We’ll also keep you posted. In the meantime, contact us if you need anything!

**Comment by ghost** [comment]
https://www.reddit.com/r/Wordpress/comments/1fqw2eh/automattic_is_suing_festingervault_i_have_not/
